language: python
git:
  submodules: false

matrix:
  include:
    - name: "Python 3.7.4 on Ubuntu 18.04 LTS (Bionic)"
      dist: bionic
      python: 3.7.4

    - name: "Python 3.7.4 on macOS 10.14.4"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

install:
  - "pip3 install pipenv"   # all three OSes agree about 'pip3'
  - "pipenv install --dev"
  - "pipenv run pip install channels"
  - "cd Shogi"
  - "./manage.py makemigrations Shogi_app"
  - "./manage.py migrate"

script: ./manage.py test

