language: python
git:
  submodules: false

matrix:
  include:
    - name: "Python 3.7.4 on Ubuntu 18.04 LTS (Bionic)"
      dist: bionic
      python: 3.7.4

install:
  - "pip3 install pipenv"   # all two OSes agree about 'pip3'
  - "pipenv install --dev"
  - "pipenv run pip install channels"
  - "cd Shogi"
  - "python3 manage.py makemigrations Shogi_app"
  - "python3 manage.py migrate"

script: python3 manage.py test

